# Generated by Django 5.1.2 on 2024-10-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
