# Generated by Django 5.1.2 on 2024-11-09 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_list', '0002_game_delete_book'),
        ('reviews', '0005_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
            preserve_default=False,
        ),
    ]
