# Generated by Django 5.1.2 on 2024-11-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_list', '0003_game_rating_game_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='review',
        ),
    ]
