# Generated by Django 5.1.1 on 2024-12-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_list', '0005_gamedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='supported_languages',
            field=models.TextField(default='bruh'),
        ),
    ]
