# Generated by Django 5.1.1 on 2024-12-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_list', '0006_gamedata_supported_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='detailed_description',
            field=models.TextField(default='no description was provided'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='header_image',
            field=models.URLField(default='no header image was provided'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='short_description',
            field=models.TextField(default='no description was provided'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='supported_languages',
            field=models.TextField(default='english'),
        ),
    ]
