# Generated by Django 4.2.17 on 2024-12-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_list', '0007_alter_gamedata_detailed_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='price_currency',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='price_discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='price_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='price_final_formatted',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='price_initial',
            field=models.IntegerField(default=0),
        ),
    ]
