# Generated by Django 5.1.2 on 2024-11-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_author_remove_review_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='review',
        ),
    ]
