# Generated by Django 5.2.dev20241216124221 on 2024-12-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_rename_review_oreview'),
        ('reviews', '0008_review_likes'),
    ]

    operations = [
    ]
